/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.Pulsar_test.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** CQL UDT type */
@org.apache.avro.specific.AvroGenerated
public class CdcAuxiliaryData extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1248926728185711885L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CdcAuxiliaryData\",\"namespace\":\"com.example.Pulsar_test.model\",\"doc\":\"CQL UDT type\",\"fields\":[{\"name\":\"account_number\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"origin_facility_code\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"destination_facility_code\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<CdcAuxiliaryData> ENCODER =
      new BinaryMessageEncoder<CdcAuxiliaryData>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CdcAuxiliaryData> DECODER =
      new BinaryMessageDecoder<CdcAuxiliaryData>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<CdcAuxiliaryData> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<CdcAuxiliaryData> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<CdcAuxiliaryData> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<CdcAuxiliaryData>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this CdcAuxiliaryData to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a CdcAuxiliaryData from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a CdcAuxiliaryData instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static CdcAuxiliaryData fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence account_number;
  @Deprecated public java.lang.CharSequence origin_facility_code;
  @Deprecated public java.lang.CharSequence destination_facility_code;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CdcAuxiliaryData() {}

  /**
   * All-args constructor.
   * @param account_number The new value for account_number
   * @param origin_facility_code The new value for origin_facility_code
   * @param destination_facility_code The new value for destination_facility_code
   */
  public CdcAuxiliaryData(java.lang.CharSequence account_number, java.lang.CharSequence origin_facility_code, java.lang.CharSequence destination_facility_code) {
    this.account_number = account_number;
    this.origin_facility_code = origin_facility_code;
    this.destination_facility_code = destination_facility_code;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return account_number;
    case 1: return origin_facility_code;
    case 2: return destination_facility_code;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: account_number = (java.lang.CharSequence)value$; break;
    case 1: origin_facility_code = (java.lang.CharSequence)value$; break;
    case 2: destination_facility_code = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'account_number' field.
   * @return The value of the 'account_number' field.
   */
  public java.lang.CharSequence getAccountNumber() {
    return account_number;
  }


  /**
   * Sets the value of the 'account_number' field.
   * @param value the value to set.
   */
  public void setAccountNumber(java.lang.CharSequence value) {
    this.account_number = value;
  }

  /**
   * Gets the value of the 'origin_facility_code' field.
   * @return The value of the 'origin_facility_code' field.
   */
  public java.lang.CharSequence getOriginFacilityCode() {
    return origin_facility_code;
  }


  /**
   * Sets the value of the 'origin_facility_code' field.
   * @param value the value to set.
   */
  public void setOriginFacilityCode(java.lang.CharSequence value) {
    this.origin_facility_code = value;
  }

  /**
   * Gets the value of the 'destination_facility_code' field.
   * @return The value of the 'destination_facility_code' field.
   */
  public java.lang.CharSequence getDestinationFacilityCode() {
    return destination_facility_code;
  }


  /**
   * Sets the value of the 'destination_facility_code' field.
   * @param value the value to set.
   */
  public void setDestinationFacilityCode(java.lang.CharSequence value) {
    this.destination_facility_code = value;
  }

  /**
   * Creates a new CdcAuxiliaryData RecordBuilder.
   * @return A new CdcAuxiliaryData RecordBuilder
   */
  public static com.example.Pulsar_test.model.CdcAuxiliaryData.Builder newBuilder() {
    return new com.example.Pulsar_test.model.CdcAuxiliaryData.Builder();
  }

  /**
   * Creates a new CdcAuxiliaryData RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CdcAuxiliaryData RecordBuilder
   */
  public static com.example.Pulsar_test.model.CdcAuxiliaryData.Builder newBuilder(com.example.Pulsar_test.model.CdcAuxiliaryData.Builder other) {
    if (other == null) {
      return new com.example.Pulsar_test.model.CdcAuxiliaryData.Builder();
    } else {
      return new com.example.Pulsar_test.model.CdcAuxiliaryData.Builder(other);
    }
  }

  /**
   * Creates a new CdcAuxiliaryData RecordBuilder by copying an existing CdcAuxiliaryData instance.
   * @param other The existing instance to copy.
   * @return A new CdcAuxiliaryData RecordBuilder
   */
  public static com.example.Pulsar_test.model.CdcAuxiliaryData.Builder newBuilder(com.example.Pulsar_test.model.CdcAuxiliaryData other) {
    if (other == null) {
      return new com.example.Pulsar_test.model.CdcAuxiliaryData.Builder();
    } else {
      return new com.example.Pulsar_test.model.CdcAuxiliaryData.Builder(other);
    }
  }

  /**
   * RecordBuilder for CdcAuxiliaryData instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CdcAuxiliaryData>
    implements org.apache.avro.data.RecordBuilder<CdcAuxiliaryData> {

    private java.lang.CharSequence account_number;
    private java.lang.CharSequence origin_facility_code;
    private java.lang.CharSequence destination_facility_code;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.Pulsar_test.model.CdcAuxiliaryData.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.account_number)) {
        this.account_number = data().deepCopy(fields()[0].schema(), other.account_number);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.origin_facility_code)) {
        this.origin_facility_code = data().deepCopy(fields()[1].schema(), other.origin_facility_code);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.destination_facility_code)) {
        this.destination_facility_code = data().deepCopy(fields()[2].schema(), other.destination_facility_code);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing CdcAuxiliaryData instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.Pulsar_test.model.CdcAuxiliaryData other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.account_number)) {
        this.account_number = data().deepCopy(fields()[0].schema(), other.account_number);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.origin_facility_code)) {
        this.origin_facility_code = data().deepCopy(fields()[1].schema(), other.origin_facility_code);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.destination_facility_code)) {
        this.destination_facility_code = data().deepCopy(fields()[2].schema(), other.destination_facility_code);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'account_number' field.
      * @return The value.
      */
    public java.lang.CharSequence getAccountNumber() {
      return account_number;
    }


    /**
      * Sets the value of the 'account_number' field.
      * @param value The value of 'account_number'.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.CdcAuxiliaryData.Builder setAccountNumber(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.account_number = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'account_number' field has been set.
      * @return True if the 'account_number' field has been set, false otherwise.
      */
    public boolean hasAccountNumber() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'account_number' field.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.CdcAuxiliaryData.Builder clearAccountNumber() {
      account_number = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'origin_facility_code' field.
      * @return The value.
      */
    public java.lang.CharSequence getOriginFacilityCode() {
      return origin_facility_code;
    }


    /**
      * Sets the value of the 'origin_facility_code' field.
      * @param value The value of 'origin_facility_code'.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.CdcAuxiliaryData.Builder setOriginFacilityCode(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.origin_facility_code = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'origin_facility_code' field has been set.
      * @return True if the 'origin_facility_code' field has been set, false otherwise.
      */
    public boolean hasOriginFacilityCode() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'origin_facility_code' field.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.CdcAuxiliaryData.Builder clearOriginFacilityCode() {
      origin_facility_code = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'destination_facility_code' field.
      * @return The value.
      */
    public java.lang.CharSequence getDestinationFacilityCode() {
      return destination_facility_code;
    }


    /**
      * Sets the value of the 'destination_facility_code' field.
      * @param value The value of 'destination_facility_code'.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.CdcAuxiliaryData.Builder setDestinationFacilityCode(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.destination_facility_code = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'destination_facility_code' field has been set.
      * @return True if the 'destination_facility_code' field has been set, false otherwise.
      */
    public boolean hasDestinationFacilityCode() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'destination_facility_code' field.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.CdcAuxiliaryData.Builder clearDestinationFacilityCode() {
      destination_facility_code = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CdcAuxiliaryData build() {
      try {
        CdcAuxiliaryData record = new CdcAuxiliaryData();
        record.account_number = fieldSetFlags()[0] ? this.account_number : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.origin_facility_code = fieldSetFlags()[1] ? this.origin_facility_code : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.destination_facility_code = fieldSetFlags()[2] ? this.destination_facility_code : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CdcAuxiliaryData>
    WRITER$ = (org.apache.avro.io.DatumWriter<CdcAuxiliaryData>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CdcAuxiliaryData>
    READER$ = (org.apache.avro.io.DatumReader<CdcAuxiliaryData>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.account_number == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.account_number);
    }

    if (this.origin_facility_code == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.origin_facility_code);
    }

    if (this.destination_facility_code == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.destination_facility_code);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.account_number = null;
      } else {
        this.account_number = in.readString(this.account_number instanceof Utf8 ? (Utf8)this.account_number : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.origin_facility_code = null;
      } else {
        this.origin_facility_code = in.readString(this.origin_facility_code instanceof Utf8 ? (Utf8)this.origin_facility_code : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.destination_facility_code = null;
      } else {
        this.destination_facility_code = in.readString(this.destination_facility_code instanceof Utf8 ? (Utf8)this.destination_facility_code : null);
      }

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.account_number = null;
          } else {
            this.account_number = in.readString(this.account_number instanceof Utf8 ? (Utf8)this.account_number : null);
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.origin_facility_code = null;
          } else {
            this.origin_facility_code = in.readString(this.origin_facility_code instanceof Utf8 ? (Utf8)this.origin_facility_code : null);
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.destination_facility_code = null;
          } else {
            this.destination_facility_code = in.readString(this.destination_facility_code instanceof Utf8 ? (Utf8)this.destination_facility_code : null);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










