/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.Pulsar_test.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** CQL UDT type */
@org.apache.avro.specific.AvroGenerated
public class CdcServiceInformation extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4682503115215204203L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CdcServiceInformation\",\"namespace\":\"com.example.Pulsar_test.model\",\"doc\":\"CQL UDT type\",\"fields\":[{\"name\":\"service_level\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"parcel_count\",\"type\":[\"null\",\"int\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<CdcServiceInformation> ENCODER =
      new BinaryMessageEncoder<CdcServiceInformation>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CdcServiceInformation> DECODER =
      new BinaryMessageDecoder<CdcServiceInformation>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<CdcServiceInformation> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<CdcServiceInformation> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<CdcServiceInformation> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<CdcServiceInformation>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this CdcServiceInformation to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a CdcServiceInformation from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a CdcServiceInformation instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static CdcServiceInformation fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence service_level;
  @Deprecated public java.lang.Integer parcel_count;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CdcServiceInformation() {}

  /**
   * All-args constructor.
   * @param service_level The new value for service_level
   * @param parcel_count The new value for parcel_count
   */
  public CdcServiceInformation(java.lang.CharSequence service_level, java.lang.Integer parcel_count) {
    this.service_level = service_level;
    this.parcel_count = parcel_count;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return service_level;
    case 1: return parcel_count;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: service_level = (java.lang.CharSequence)value$; break;
    case 1: parcel_count = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'service_level' field.
   * @return The value of the 'service_level' field.
   */
  public java.lang.CharSequence getServiceLevel() {
    return service_level;
  }


  /**
   * Sets the value of the 'service_level' field.
   * @param value the value to set.
   */
  public void setServiceLevel(java.lang.CharSequence value) {
    this.service_level = value;
  }

  /**
   * Gets the value of the 'parcel_count' field.
   * @return The value of the 'parcel_count' field.
   */
  public java.lang.Integer getParcelCount() {
    return parcel_count;
  }


  /**
   * Sets the value of the 'parcel_count' field.
   * @param value the value to set.
   */
  public void setParcelCount(java.lang.Integer value) {
    this.parcel_count = value;
  }

  /**
   * Creates a new CdcServiceInformation RecordBuilder.
   * @return A new CdcServiceInformation RecordBuilder
   */
  public static com.example.Pulsar_test.model.CdcServiceInformation.Builder newBuilder() {
    return new com.example.Pulsar_test.model.CdcServiceInformation.Builder();
  }

  /**
   * Creates a new CdcServiceInformation RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CdcServiceInformation RecordBuilder
   */
  public static com.example.Pulsar_test.model.CdcServiceInformation.Builder newBuilder(com.example.Pulsar_test.model.CdcServiceInformation.Builder other) {
    if (other == null) {
      return new com.example.Pulsar_test.model.CdcServiceInformation.Builder();
    } else {
      return new com.example.Pulsar_test.model.CdcServiceInformation.Builder(other);
    }
  }

  /**
   * Creates a new CdcServiceInformation RecordBuilder by copying an existing CdcServiceInformation instance.
   * @param other The existing instance to copy.
   * @return A new CdcServiceInformation RecordBuilder
   */
  public static com.example.Pulsar_test.model.CdcServiceInformation.Builder newBuilder(com.example.Pulsar_test.model.CdcServiceInformation other) {
    if (other == null) {
      return new com.example.Pulsar_test.model.CdcServiceInformation.Builder();
    } else {
      return new com.example.Pulsar_test.model.CdcServiceInformation.Builder(other);
    }
  }

  /**
   * RecordBuilder for CdcServiceInformation instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CdcServiceInformation>
    implements org.apache.avro.data.RecordBuilder<CdcServiceInformation> {

    private java.lang.CharSequence service_level;
    private java.lang.Integer parcel_count;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.Pulsar_test.model.CdcServiceInformation.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.service_level)) {
        this.service_level = data().deepCopy(fields()[0].schema(), other.service_level);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.parcel_count)) {
        this.parcel_count = data().deepCopy(fields()[1].schema(), other.parcel_count);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing CdcServiceInformation instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.Pulsar_test.model.CdcServiceInformation other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.service_level)) {
        this.service_level = data().deepCopy(fields()[0].schema(), other.service_level);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.parcel_count)) {
        this.parcel_count = data().deepCopy(fields()[1].schema(), other.parcel_count);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'service_level' field.
      * @return The value.
      */
    public java.lang.CharSequence getServiceLevel() {
      return service_level;
    }


    /**
      * Sets the value of the 'service_level' field.
      * @param value The value of 'service_level'.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.CdcServiceInformation.Builder setServiceLevel(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.service_level = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'service_level' field has been set.
      * @return True if the 'service_level' field has been set, false otherwise.
      */
    public boolean hasServiceLevel() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'service_level' field.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.CdcServiceInformation.Builder clearServiceLevel() {
      service_level = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'parcel_count' field.
      * @return The value.
      */
    public java.lang.Integer getParcelCount() {
      return parcel_count;
    }


    /**
      * Sets the value of the 'parcel_count' field.
      * @param value The value of 'parcel_count'.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.CdcServiceInformation.Builder setParcelCount(java.lang.Integer value) {
      validate(fields()[1], value);
      this.parcel_count = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'parcel_count' field has been set.
      * @return True if the 'parcel_count' field has been set, false otherwise.
      */
    public boolean hasParcelCount() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'parcel_count' field.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.CdcServiceInformation.Builder clearParcelCount() {
      parcel_count = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CdcServiceInformation build() {
      try {
        CdcServiceInformation record = new CdcServiceInformation();
        record.service_level = fieldSetFlags()[0] ? this.service_level : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.parcel_count = fieldSetFlags()[1] ? this.parcel_count : (java.lang.Integer) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CdcServiceInformation>
    WRITER$ = (org.apache.avro.io.DatumWriter<CdcServiceInformation>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CdcServiceInformation>
    READER$ = (org.apache.avro.io.DatumReader<CdcServiceInformation>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.service_level == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.service_level);
    }

    if (this.parcel_count == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeInt(this.parcel_count);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.service_level = null;
      } else {
        this.service_level = in.readString(this.service_level instanceof Utf8 ? (Utf8)this.service_level : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.parcel_count = null;
      } else {
        this.parcel_count = in.readInt();
      }

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.service_level = null;
          } else {
            this.service_level = in.readString(this.service_level instanceof Utf8 ? (Utf8)this.service_level : null);
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.parcel_count = null;
          } else {
            this.parcel_count = in.readInt();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










