/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.Pulsar_test.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Table 63353437396533612d396630362d346635352d626235312d303766386633616630633037_sortation.container_history */
@org.apache.avro.specific.AvroGenerated
public class ContainerHistoryKey extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4425156938588695241L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ContainerHistoryKey\",\"namespace\":\"com.example.Pulsar_test.model\",\"doc\":\"Table 63353437396533612d396630362d346635352d626235312d303766386633616630633037_sortation.container_history\",\"fields\":[{\"name\":\"container_id\",\"type\":\"string\"},{\"name\":\"node_id\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"status\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"created_at\",\"type\":[\"null\",\"long\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ContainerHistoryKey> ENCODER =
      new BinaryMessageEncoder<ContainerHistoryKey>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ContainerHistoryKey> DECODER =
      new BinaryMessageDecoder<ContainerHistoryKey>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ContainerHistoryKey> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ContainerHistoryKey> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ContainerHistoryKey> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ContainerHistoryKey>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ContainerHistoryKey to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ContainerHistoryKey from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ContainerHistoryKey instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ContainerHistoryKey fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence container_id;
  @Deprecated public java.lang.CharSequence node_id;
  @Deprecated public java.lang.CharSequence status;
  @Deprecated public java.lang.Long created_at;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ContainerHistoryKey() {}

  /**
   * All-args constructor.
   * @param container_id The new value for container_id
   * @param node_id The new value for node_id
   * @param status The new value for status
   * @param created_at The new value for created_at
   */
  public ContainerHistoryKey(java.lang.CharSequence container_id, java.lang.CharSequence node_id, java.lang.CharSequence status, java.lang.Long created_at) {
    this.container_id = container_id;
    this.node_id = node_id;
    this.status = status;
    this.created_at = created_at;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return container_id;
    case 1: return node_id;
    case 2: return status;
    case 3: return created_at;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: container_id = (java.lang.CharSequence)value$; break;
    case 1: node_id = (java.lang.CharSequence)value$; break;
    case 2: status = (java.lang.CharSequence)value$; break;
    case 3: created_at = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'container_id' field.
   * @return The value of the 'container_id' field.
   */
  public java.lang.CharSequence getContainerId() {
    return container_id;
  }


  /**
   * Sets the value of the 'container_id' field.
   * @param value the value to set.
   */
  public void setContainerId(java.lang.CharSequence value) {
    this.container_id = value;
  }

  /**
   * Gets the value of the 'node_id' field.
   * @return The value of the 'node_id' field.
   */
  public java.lang.CharSequence getNodeId() {
    return node_id;
  }


  /**
   * Sets the value of the 'node_id' field.
   * @param value the value to set.
   */
  public void setNodeId(java.lang.CharSequence value) {
    this.node_id = value;
  }

  /**
   * Gets the value of the 'status' field.
   * @return The value of the 'status' field.
   */
  public java.lang.CharSequence getStatus() {
    return status;
  }


  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(java.lang.CharSequence value) {
    this.status = value;
  }

  /**
   * Gets the value of the 'created_at' field.
   * @return The value of the 'created_at' field.
   */
  public java.lang.Long getCreatedAt() {
    return created_at;
  }


  /**
   * Sets the value of the 'created_at' field.
   * @param value the value to set.
   */
  public void setCreatedAt(java.lang.Long value) {
    this.created_at = value;
  }

  /**
   * Creates a new ContainerHistoryKey RecordBuilder.
   * @return A new ContainerHistoryKey RecordBuilder
   */
  public static com.example.Pulsar_test.model.ContainerHistoryKey.Builder newBuilder() {
    return new com.example.Pulsar_test.model.ContainerHistoryKey.Builder();
  }

  /**
   * Creates a new ContainerHistoryKey RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ContainerHistoryKey RecordBuilder
   */
  public static com.example.Pulsar_test.model.ContainerHistoryKey.Builder newBuilder(com.example.Pulsar_test.model.ContainerHistoryKey.Builder other) {
    if (other == null) {
      return new com.example.Pulsar_test.model.ContainerHistoryKey.Builder();
    } else {
      return new com.example.Pulsar_test.model.ContainerHistoryKey.Builder(other);
    }
  }

  /**
   * Creates a new ContainerHistoryKey RecordBuilder by copying an existing ContainerHistoryKey instance.
   * @param other The existing instance to copy.
   * @return A new ContainerHistoryKey RecordBuilder
   */
  public static com.example.Pulsar_test.model.ContainerHistoryKey.Builder newBuilder(com.example.Pulsar_test.model.ContainerHistoryKey other) {
    if (other == null) {
      return new com.example.Pulsar_test.model.ContainerHistoryKey.Builder();
    } else {
      return new com.example.Pulsar_test.model.ContainerHistoryKey.Builder(other);
    }
  }

  /**
   * RecordBuilder for ContainerHistoryKey instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ContainerHistoryKey>
    implements org.apache.avro.data.RecordBuilder<ContainerHistoryKey> {

    private java.lang.CharSequence container_id;
    private java.lang.CharSequence node_id;
    private java.lang.CharSequence status;
    private java.lang.Long created_at;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.Pulsar_test.model.ContainerHistoryKey.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.container_id)) {
        this.container_id = data().deepCopy(fields()[0].schema(), other.container_id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.node_id)) {
        this.node_id = data().deepCopy(fields()[1].schema(), other.node_id);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.status)) {
        this.status = data().deepCopy(fields()[2].schema(), other.status);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.created_at)) {
        this.created_at = data().deepCopy(fields()[3].schema(), other.created_at);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing ContainerHistoryKey instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.Pulsar_test.model.ContainerHistoryKey other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.container_id)) {
        this.container_id = data().deepCopy(fields()[0].schema(), other.container_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.node_id)) {
        this.node_id = data().deepCopy(fields()[1].schema(), other.node_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.status)) {
        this.status = data().deepCopy(fields()[2].schema(), other.status);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.created_at)) {
        this.created_at = data().deepCopy(fields()[3].schema(), other.created_at);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'container_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getContainerId() {
      return container_id;
    }


    /**
      * Sets the value of the 'container_id' field.
      * @param value The value of 'container_id'.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.ContainerHistoryKey.Builder setContainerId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.container_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'container_id' field has been set.
      * @return True if the 'container_id' field has been set, false otherwise.
      */
    public boolean hasContainerId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'container_id' field.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.ContainerHistoryKey.Builder clearContainerId() {
      container_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'node_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getNodeId() {
      return node_id;
    }


    /**
      * Sets the value of the 'node_id' field.
      * @param value The value of 'node_id'.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.ContainerHistoryKey.Builder setNodeId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.node_id = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'node_id' field has been set.
      * @return True if the 'node_id' field has been set, false otherwise.
      */
    public boolean hasNodeId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'node_id' field.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.ContainerHistoryKey.Builder clearNodeId() {
      node_id = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'status' field.
      * @return The value.
      */
    public java.lang.CharSequence getStatus() {
      return status;
    }


    /**
      * Sets the value of the 'status' field.
      * @param value The value of 'status'.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.ContainerHistoryKey.Builder setStatus(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.status = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'status' field.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.ContainerHistoryKey.Builder clearStatus() {
      status = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'created_at' field.
      * @return The value.
      */
    public java.lang.Long getCreatedAt() {
      return created_at;
    }


    /**
      * Sets the value of the 'created_at' field.
      * @param value The value of 'created_at'.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.ContainerHistoryKey.Builder setCreatedAt(java.lang.Long value) {
      validate(fields()[3], value);
      this.created_at = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'created_at' field has been set.
      * @return True if the 'created_at' field has been set, false otherwise.
      */
    public boolean hasCreatedAt() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'created_at' field.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.ContainerHistoryKey.Builder clearCreatedAt() {
      created_at = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ContainerHistoryKey build() {
      try {
        ContainerHistoryKey record = new ContainerHistoryKey();
        record.container_id = fieldSetFlags()[0] ? this.container_id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.node_id = fieldSetFlags()[1] ? this.node_id : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.status = fieldSetFlags()[2] ? this.status : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.created_at = fieldSetFlags()[3] ? this.created_at : (java.lang.Long) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ContainerHistoryKey>
    WRITER$ = (org.apache.avro.io.DatumWriter<ContainerHistoryKey>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ContainerHistoryKey>
    READER$ = (org.apache.avro.io.DatumReader<ContainerHistoryKey>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.container_id);

    if (this.node_id == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.node_id);
    }

    if (this.status == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.status);
    }

    if (this.created_at == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.created_at);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.container_id = in.readString(this.container_id instanceof Utf8 ? (Utf8)this.container_id : null);

      if (in.readIndex() != 1) {
        in.readNull();
        this.node_id = null;
      } else {
        this.node_id = in.readString(this.node_id instanceof Utf8 ? (Utf8)this.node_id : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.status = null;
      } else {
        this.status = in.readString(this.status instanceof Utf8 ? (Utf8)this.status : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.created_at = null;
      } else {
        this.created_at = in.readLong();
      }

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.container_id = in.readString(this.container_id instanceof Utf8 ? (Utf8)this.container_id : null);
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.node_id = null;
          } else {
            this.node_id = in.readString(this.node_id instanceof Utf8 ? (Utf8)this.node_id : null);
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.status = null;
          } else {
            this.status = in.readString(this.status instanceof Utf8 ? (Utf8)this.status : null);
          }
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.created_at = null;
          } else {
            this.created_at = in.readLong();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










