/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.Pulsar_test.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Table 38393236353635392d373833652d346333392d626338382d316162383932613364353731_sortation.container */
@org.apache.avro.specific.AvroGenerated
public class ContainerValue extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5184506942358576254L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ContainerValue\",\"namespace\":\"com.example.Pulsar_test.model\",\"doc\":\"Table 38393236353635392d373833652d346333392d626338382d316162383932613364353731_sortation.container\",\"fields\":[{\"name\":\"auxiliary_data\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"AuxiliaryData\",\"doc\":\"CQL UDT type\",\"fields\":[{\"name\":\"account_number\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"origin_facility_code\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"destination_facility_code\",\"type\":[\"null\",\"string\"],\"default\":null}]}],\"default\":null},{\"name\":\"reference1\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"reference2\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"reference3\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"created_at\",\"type\":[\"null\",{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}],\"default\":null},{\"name\":\"nodes\",\"type\":[\"null\",{\"type\":\"array\",\"items\":[\"null\",\"string\"]}],\"default\":null},{\"name\":\"service_code\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"container_type\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"carrier_tracking_number\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"airterra_tracking_number\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"active_node_id\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"container_barcode\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"shipper_parcel_number\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();
static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<ContainerValue> ENCODER =
      new BinaryMessageEncoder<ContainerValue>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ContainerValue> DECODER =
      new BinaryMessageDecoder<ContainerValue>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ContainerValue> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ContainerValue> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ContainerValue> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ContainerValue>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ContainerValue to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ContainerValue from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ContainerValue instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ContainerValue fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public com.example.Pulsar_test.model.AuxiliaryData auxiliary_data;
  @Deprecated public java.lang.CharSequence reference1;
  @Deprecated public java.lang.CharSequence reference2;
  @Deprecated public java.lang.CharSequence reference3;
  @Deprecated public java.time.Instant created_at;
  @Deprecated public java.util.List<java.lang.CharSequence> nodes;
  @Deprecated public java.lang.CharSequence service_code;
  @Deprecated public java.lang.CharSequence container_type;
  @Deprecated public java.lang.CharSequence carrier_tracking_number;
  @Deprecated public java.lang.CharSequence airterra_tracking_number;
  @Deprecated public java.lang.CharSequence active_node_id;
  @Deprecated public java.lang.CharSequence container_barcode;
  @Deprecated public java.lang.CharSequence shipper_parcel_number;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ContainerValue() {}

  /**
   * All-args constructor.
   * @param auxiliary_data The new value for auxiliary_data
   * @param reference1 The new value for reference1
   * @param reference2 The new value for reference2
   * @param reference3 The new value for reference3
   * @param created_at The new value for created_at
   * @param nodes The new value for nodes
   * @param service_code The new value for service_code
   * @param container_type The new value for container_type
   * @param carrier_tracking_number The new value for carrier_tracking_number
   * @param airterra_tracking_number The new value for airterra_tracking_number
   * @param active_node_id The new value for active_node_id
   * @param container_barcode The new value for container_barcode
   * @param shipper_parcel_number The new value for shipper_parcel_number
   */
  public ContainerValue(com.example.Pulsar_test.model.AuxiliaryData auxiliary_data, java.lang.CharSequence reference1, java.lang.CharSequence reference2, java.lang.CharSequence reference3, java.time.Instant created_at, java.util.List<java.lang.CharSequence> nodes, java.lang.CharSequence service_code, java.lang.CharSequence container_type, java.lang.CharSequence carrier_tracking_number, java.lang.CharSequence airterra_tracking_number, java.lang.CharSequence active_node_id, java.lang.CharSequence container_barcode, java.lang.CharSequence shipper_parcel_number) {
    this.auxiliary_data = auxiliary_data;
    this.reference1 = reference1;
    this.reference2 = reference2;
    this.reference3 = reference3;
    this.created_at = created_at;
    this.nodes = nodes;
    this.service_code = service_code;
    this.container_type = container_type;
    this.carrier_tracking_number = carrier_tracking_number;
    this.airterra_tracking_number = airterra_tracking_number;
    this.active_node_id = active_node_id;
    this.container_barcode = container_barcode;
    this.shipper_parcel_number = shipper_parcel_number;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return auxiliary_data;
    case 1: return reference1;
    case 2: return reference2;
    case 3: return reference3;
    case 4: return created_at;
    case 5: return nodes;
    case 6: return service_code;
    case 7: return container_type;
    case 8: return carrier_tracking_number;
    case 9: return airterra_tracking_number;
    case 10: return active_node_id;
    case 11: return container_barcode;
    case 12: return shipper_parcel_number;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: auxiliary_data = (com.example.Pulsar_test.model.AuxiliaryData)value$; break;
    case 1: reference1 = (java.lang.CharSequence)value$; break;
    case 2: reference2 = (java.lang.CharSequence)value$; break;
    case 3: reference3 = (java.lang.CharSequence)value$; break;
    case 4: created_at = (java.time.Instant)value$; break;
    case 5: nodes = (java.util.List<java.lang.CharSequence>)value$; break;
    case 6: service_code = (java.lang.CharSequence)value$; break;
    case 7: container_type = (java.lang.CharSequence)value$; break;
    case 8: carrier_tracking_number = (java.lang.CharSequence)value$; break;
    case 9: airterra_tracking_number = (java.lang.CharSequence)value$; break;
    case 10: active_node_id = (java.lang.CharSequence)value$; break;
    case 11: container_barcode = (java.lang.CharSequence)value$; break;
    case 12: shipper_parcel_number = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'auxiliary_data' field.
   * @return The value of the 'auxiliary_data' field.
   */
  public com.example.Pulsar_test.model.AuxiliaryData getAuxiliaryData() {
    return auxiliary_data;
  }


  /**
   * Sets the value of the 'auxiliary_data' field.
   * @param value the value to set.
   */
  public void setAuxiliaryData(com.example.Pulsar_test.model.AuxiliaryData value) {
    this.auxiliary_data = value;
  }

  /**
   * Gets the value of the 'reference1' field.
   * @return The value of the 'reference1' field.
   */
  public java.lang.CharSequence getReference1() {
    return reference1;
  }


  /**
   * Sets the value of the 'reference1' field.
   * @param value the value to set.
   */
  public void setReference1(java.lang.CharSequence value) {
    this.reference1 = value;
  }

  /**
   * Gets the value of the 'reference2' field.
   * @return The value of the 'reference2' field.
   */
  public java.lang.CharSequence getReference2() {
    return reference2;
  }


  /**
   * Sets the value of the 'reference2' field.
   * @param value the value to set.
   */
  public void setReference2(java.lang.CharSequence value) {
    this.reference2 = value;
  }

  /**
   * Gets the value of the 'reference3' field.
   * @return The value of the 'reference3' field.
   */
  public java.lang.CharSequence getReference3() {
    return reference3;
  }


  /**
   * Sets the value of the 'reference3' field.
   * @param value the value to set.
   */
  public void setReference3(java.lang.CharSequence value) {
    this.reference3 = value;
  }

  /**
   * Gets the value of the 'created_at' field.
   * @return The value of the 'created_at' field.
   */
  public java.time.Instant getCreatedAt() {
    return created_at;
  }


  /**
   * Sets the value of the 'created_at' field.
   * @param value the value to set.
   */
  public void setCreatedAt(java.time.Instant value) {
    this.created_at = value;
  }

  /**
   * Gets the value of the 'nodes' field.
   * @return The value of the 'nodes' field.
   */
  public java.util.List<java.lang.CharSequence> getNodes() {
    return nodes;
  }


  /**
   * Sets the value of the 'nodes' field.
   * @param value the value to set.
   */
  public void setNodes(java.util.List<java.lang.CharSequence> value) {
    this.nodes = value;
  }

  /**
   * Gets the value of the 'service_code' field.
   * @return The value of the 'service_code' field.
   */
  public java.lang.CharSequence getServiceCode() {
    return service_code;
  }


  /**
   * Sets the value of the 'service_code' field.
   * @param value the value to set.
   */
  public void setServiceCode(java.lang.CharSequence value) {
    this.service_code = value;
  }

  /**
   * Gets the value of the 'container_type' field.
   * @return The value of the 'container_type' field.
   */
  public java.lang.CharSequence getContainerType() {
    return container_type;
  }


  /**
   * Sets the value of the 'container_type' field.
   * @param value the value to set.
   */
  public void setContainerType(java.lang.CharSequence value) {
    this.container_type = value;
  }

  /**
   * Gets the value of the 'carrier_tracking_number' field.
   * @return The value of the 'carrier_tracking_number' field.
   */
  public java.lang.CharSequence getCarrierTrackingNumber() {
    return carrier_tracking_number;
  }


  /**
   * Sets the value of the 'carrier_tracking_number' field.
   * @param value the value to set.
   */
  public void setCarrierTrackingNumber(java.lang.CharSequence value) {
    this.carrier_tracking_number = value;
  }

  /**
   * Gets the value of the 'airterra_tracking_number' field.
   * @return The value of the 'airterra_tracking_number' field.
   */
  public java.lang.CharSequence getAirterraTrackingNumber() {
    return airterra_tracking_number;
  }


  /**
   * Sets the value of the 'airterra_tracking_number' field.
   * @param value the value to set.
   */
  public void setAirterraTrackingNumber(java.lang.CharSequence value) {
    this.airterra_tracking_number = value;
  }

  /**
   * Gets the value of the 'active_node_id' field.
   * @return The value of the 'active_node_id' field.
   */
  public java.lang.CharSequence getActiveNodeId() {
    return active_node_id;
  }


  /**
   * Sets the value of the 'active_node_id' field.
   * @param value the value to set.
   */
  public void setActiveNodeId(java.lang.CharSequence value) {
    this.active_node_id = value;
  }

  /**
   * Gets the value of the 'container_barcode' field.
   * @return The value of the 'container_barcode' field.
   */
  public java.lang.CharSequence getContainerBarcode() {
    return container_barcode;
  }


  /**
   * Sets the value of the 'container_barcode' field.
   * @param value the value to set.
   */
  public void setContainerBarcode(java.lang.CharSequence value) {
    this.container_barcode = value;
  }

  /**
   * Gets the value of the 'shipper_parcel_number' field.
   * @return The value of the 'shipper_parcel_number' field.
   */
  public java.lang.CharSequence getShipperParcelNumber() {
    return shipper_parcel_number;
  }


  /**
   * Sets the value of the 'shipper_parcel_number' field.
   * @param value the value to set.
   */
  public void setShipperParcelNumber(java.lang.CharSequence value) {
    this.shipper_parcel_number = value;
  }

  /**
   * Creates a new ContainerValue RecordBuilder.
   * @return A new ContainerValue RecordBuilder
   */
  public static com.example.Pulsar_test.model.ContainerValue.Builder newBuilder() {
    return new com.example.Pulsar_test.model.ContainerValue.Builder();
  }

  /**
   * Creates a new ContainerValue RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ContainerValue RecordBuilder
   */
  public static com.example.Pulsar_test.model.ContainerValue.Builder newBuilder(com.example.Pulsar_test.model.ContainerValue.Builder other) {
    if (other == null) {
      return new com.example.Pulsar_test.model.ContainerValue.Builder();
    } else {
      return new com.example.Pulsar_test.model.ContainerValue.Builder(other);
    }
  }

  /**
   * Creates a new ContainerValue RecordBuilder by copying an existing ContainerValue instance.
   * @param other The existing instance to copy.
   * @return A new ContainerValue RecordBuilder
   */
  public static com.example.Pulsar_test.model.ContainerValue.Builder newBuilder(com.example.Pulsar_test.model.ContainerValue other) {
    if (other == null) {
      return new com.example.Pulsar_test.model.ContainerValue.Builder();
    } else {
      return new com.example.Pulsar_test.model.ContainerValue.Builder(other);
    }
  }

  /**
   * RecordBuilder for ContainerValue instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ContainerValue>
    implements org.apache.avro.data.RecordBuilder<ContainerValue> {

    private com.example.Pulsar_test.model.AuxiliaryData auxiliary_data;
    private com.example.Pulsar_test.model.AuxiliaryData.Builder auxiliary_dataBuilder;
    private java.lang.CharSequence reference1;
    private java.lang.CharSequence reference2;
    private java.lang.CharSequence reference3;
    private java.time.Instant created_at;
    private java.util.List<java.lang.CharSequence> nodes;
    private java.lang.CharSequence service_code;
    private java.lang.CharSequence container_type;
    private java.lang.CharSequence carrier_tracking_number;
    private java.lang.CharSequence airterra_tracking_number;
    private java.lang.CharSequence active_node_id;
    private java.lang.CharSequence container_barcode;
    private java.lang.CharSequence shipper_parcel_number;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.Pulsar_test.model.ContainerValue.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.auxiliary_data)) {
        this.auxiliary_data = data().deepCopy(fields()[0].schema(), other.auxiliary_data);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (other.hasAuxiliaryDataBuilder()) {
        this.auxiliary_dataBuilder = com.example.Pulsar_test.model.AuxiliaryData.newBuilder(other.getAuxiliaryDataBuilder());
      }
      if (isValidValue(fields()[1], other.reference1)) {
        this.reference1 = data().deepCopy(fields()[1].schema(), other.reference1);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.reference2)) {
        this.reference2 = data().deepCopy(fields()[2].schema(), other.reference2);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.reference3)) {
        this.reference3 = data().deepCopy(fields()[3].schema(), other.reference3);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.created_at)) {
        this.created_at = data().deepCopy(fields()[4].schema(), other.created_at);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.nodes)) {
        this.nodes = data().deepCopy(fields()[5].schema(), other.nodes);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.service_code)) {
        this.service_code = data().deepCopy(fields()[6].schema(), other.service_code);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.container_type)) {
        this.container_type = data().deepCopy(fields()[7].schema(), other.container_type);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.carrier_tracking_number)) {
        this.carrier_tracking_number = data().deepCopy(fields()[8].schema(), other.carrier_tracking_number);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.airterra_tracking_number)) {
        this.airterra_tracking_number = data().deepCopy(fields()[9].schema(), other.airterra_tracking_number);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.active_node_id)) {
        this.active_node_id = data().deepCopy(fields()[10].schema(), other.active_node_id);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
      if (isValidValue(fields()[11], other.container_barcode)) {
        this.container_barcode = data().deepCopy(fields()[11].schema(), other.container_barcode);
        fieldSetFlags()[11] = other.fieldSetFlags()[11];
      }
      if (isValidValue(fields()[12], other.shipper_parcel_number)) {
        this.shipper_parcel_number = data().deepCopy(fields()[12].schema(), other.shipper_parcel_number);
        fieldSetFlags()[12] = other.fieldSetFlags()[12];
      }
    }

    /**
     * Creates a Builder by copying an existing ContainerValue instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.Pulsar_test.model.ContainerValue other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.auxiliary_data)) {
        this.auxiliary_data = data().deepCopy(fields()[0].schema(), other.auxiliary_data);
        fieldSetFlags()[0] = true;
      }
      this.auxiliary_dataBuilder = null;
      if (isValidValue(fields()[1], other.reference1)) {
        this.reference1 = data().deepCopy(fields()[1].schema(), other.reference1);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.reference2)) {
        this.reference2 = data().deepCopy(fields()[2].schema(), other.reference2);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.reference3)) {
        this.reference3 = data().deepCopy(fields()[3].schema(), other.reference3);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.created_at)) {
        this.created_at = data().deepCopy(fields()[4].schema(), other.created_at);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.nodes)) {
        this.nodes = data().deepCopy(fields()[5].schema(), other.nodes);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.service_code)) {
        this.service_code = data().deepCopy(fields()[6].schema(), other.service_code);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.container_type)) {
        this.container_type = data().deepCopy(fields()[7].schema(), other.container_type);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.carrier_tracking_number)) {
        this.carrier_tracking_number = data().deepCopy(fields()[8].schema(), other.carrier_tracking_number);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.airterra_tracking_number)) {
        this.airterra_tracking_number = data().deepCopy(fields()[9].schema(), other.airterra_tracking_number);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.active_node_id)) {
        this.active_node_id = data().deepCopy(fields()[10].schema(), other.active_node_id);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.container_barcode)) {
        this.container_barcode = data().deepCopy(fields()[11].schema(), other.container_barcode);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.shipper_parcel_number)) {
        this.shipper_parcel_number = data().deepCopy(fields()[12].schema(), other.shipper_parcel_number);
        fieldSetFlags()[12] = true;
      }
    }

    /**
      * Gets the value of the 'auxiliary_data' field.
      * @return The value.
      */
    public com.example.Pulsar_test.model.AuxiliaryData getAuxiliaryData() {
      return auxiliary_data;
    }


    /**
      * Sets the value of the 'auxiliary_data' field.
      * @param value The value of 'auxiliary_data'.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.ContainerValue.Builder setAuxiliaryData(com.example.Pulsar_test.model.AuxiliaryData value) {
      validate(fields()[0], value);
      this.auxiliary_dataBuilder = null;
      this.auxiliary_data = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'auxiliary_data' field has been set.
      * @return True if the 'auxiliary_data' field has been set, false otherwise.
      */
    public boolean hasAuxiliaryData() {
      return fieldSetFlags()[0];
    }

    /**
     * Gets the Builder instance for the 'auxiliary_data' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.example.Pulsar_test.model.AuxiliaryData.Builder getAuxiliaryDataBuilder() {
      if (auxiliary_dataBuilder == null) {
        if (hasAuxiliaryData()) {
          setAuxiliaryDataBuilder(com.example.Pulsar_test.model.AuxiliaryData.newBuilder(auxiliary_data));
        } else {
          setAuxiliaryDataBuilder(com.example.Pulsar_test.model.AuxiliaryData.newBuilder());
        }
      }
      return auxiliary_dataBuilder;
    }

    /**
     * Sets the Builder instance for the 'auxiliary_data' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public com.example.Pulsar_test.model.ContainerValue.Builder setAuxiliaryDataBuilder(com.example.Pulsar_test.model.AuxiliaryData.Builder value) {
      clearAuxiliaryData();
      auxiliary_dataBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'auxiliary_data' field has an active Builder instance
     * @return True if the 'auxiliary_data' field has an active Builder instance
     */
    public boolean hasAuxiliaryDataBuilder() {
      return auxiliary_dataBuilder != null;
    }

    /**
      * Clears the value of the 'auxiliary_data' field.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.ContainerValue.Builder clearAuxiliaryData() {
      auxiliary_data = null;
      auxiliary_dataBuilder = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'reference1' field.
      * @return The value.
      */
    public java.lang.CharSequence getReference1() {
      return reference1;
    }


    /**
      * Sets the value of the 'reference1' field.
      * @param value The value of 'reference1'.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.ContainerValue.Builder setReference1(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.reference1 = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'reference1' field has been set.
      * @return True if the 'reference1' field has been set, false otherwise.
      */
    public boolean hasReference1() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'reference1' field.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.ContainerValue.Builder clearReference1() {
      reference1 = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'reference2' field.
      * @return The value.
      */
    public java.lang.CharSequence getReference2() {
      return reference2;
    }


    /**
      * Sets the value of the 'reference2' field.
      * @param value The value of 'reference2'.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.ContainerValue.Builder setReference2(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.reference2 = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'reference2' field has been set.
      * @return True if the 'reference2' field has been set, false otherwise.
      */
    public boolean hasReference2() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'reference2' field.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.ContainerValue.Builder clearReference2() {
      reference2 = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'reference3' field.
      * @return The value.
      */
    public java.lang.CharSequence getReference3() {
      return reference3;
    }


    /**
      * Sets the value of the 'reference3' field.
      * @param value The value of 'reference3'.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.ContainerValue.Builder setReference3(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.reference3 = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'reference3' field has been set.
      * @return True if the 'reference3' field has been set, false otherwise.
      */
    public boolean hasReference3() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'reference3' field.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.ContainerValue.Builder clearReference3() {
      reference3 = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'created_at' field.
      * @return The value.
      */
    public java.time.Instant getCreatedAt() {
      return created_at;
    }


    /**
      * Sets the value of the 'created_at' field.
      * @param value The value of 'created_at'.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.ContainerValue.Builder setCreatedAt(java.time.Instant value) {
      validate(fields()[4], value);
      this.created_at = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'created_at' field has been set.
      * @return True if the 'created_at' field has been set, false otherwise.
      */
    public boolean hasCreatedAt() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'created_at' field.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.ContainerValue.Builder clearCreatedAt() {
      created_at = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'nodes' field.
      * @return The value.
      */
    public java.util.List<java.lang.CharSequence> getNodes() {
      return nodes;
    }


    /**
      * Sets the value of the 'nodes' field.
      * @param value The value of 'nodes'.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.ContainerValue.Builder setNodes(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[5], value);
      this.nodes = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'nodes' field has been set.
      * @return True if the 'nodes' field has been set, false otherwise.
      */
    public boolean hasNodes() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'nodes' field.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.ContainerValue.Builder clearNodes() {
      nodes = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'service_code' field.
      * @return The value.
      */
    public java.lang.CharSequence getServiceCode() {
      return service_code;
    }


    /**
      * Sets the value of the 'service_code' field.
      * @param value The value of 'service_code'.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.ContainerValue.Builder setServiceCode(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.service_code = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'service_code' field has been set.
      * @return True if the 'service_code' field has been set, false otherwise.
      */
    public boolean hasServiceCode() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'service_code' field.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.ContainerValue.Builder clearServiceCode() {
      service_code = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'container_type' field.
      * @return The value.
      */
    public java.lang.CharSequence getContainerType() {
      return container_type;
    }


    /**
      * Sets the value of the 'container_type' field.
      * @param value The value of 'container_type'.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.ContainerValue.Builder setContainerType(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.container_type = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'container_type' field has been set.
      * @return True if the 'container_type' field has been set, false otherwise.
      */
    public boolean hasContainerType() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'container_type' field.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.ContainerValue.Builder clearContainerType() {
      container_type = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'carrier_tracking_number' field.
      * @return The value.
      */
    public java.lang.CharSequence getCarrierTrackingNumber() {
      return carrier_tracking_number;
    }


    /**
      * Sets the value of the 'carrier_tracking_number' field.
      * @param value The value of 'carrier_tracking_number'.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.ContainerValue.Builder setCarrierTrackingNumber(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.carrier_tracking_number = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'carrier_tracking_number' field has been set.
      * @return True if the 'carrier_tracking_number' field has been set, false otherwise.
      */
    public boolean hasCarrierTrackingNumber() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'carrier_tracking_number' field.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.ContainerValue.Builder clearCarrierTrackingNumber() {
      carrier_tracking_number = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'airterra_tracking_number' field.
      * @return The value.
      */
    public java.lang.CharSequence getAirterraTrackingNumber() {
      return airterra_tracking_number;
    }


    /**
      * Sets the value of the 'airterra_tracking_number' field.
      * @param value The value of 'airterra_tracking_number'.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.ContainerValue.Builder setAirterraTrackingNumber(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.airterra_tracking_number = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'airterra_tracking_number' field has been set.
      * @return True if the 'airterra_tracking_number' field has been set, false otherwise.
      */
    public boolean hasAirterraTrackingNumber() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'airterra_tracking_number' field.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.ContainerValue.Builder clearAirterraTrackingNumber() {
      airterra_tracking_number = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'active_node_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getActiveNodeId() {
      return active_node_id;
    }


    /**
      * Sets the value of the 'active_node_id' field.
      * @param value The value of 'active_node_id'.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.ContainerValue.Builder setActiveNodeId(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.active_node_id = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'active_node_id' field has been set.
      * @return True if the 'active_node_id' field has been set, false otherwise.
      */
    public boolean hasActiveNodeId() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'active_node_id' field.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.ContainerValue.Builder clearActiveNodeId() {
      active_node_id = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'container_barcode' field.
      * @return The value.
      */
    public java.lang.CharSequence getContainerBarcode() {
      return container_barcode;
    }


    /**
      * Sets the value of the 'container_barcode' field.
      * @param value The value of 'container_barcode'.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.ContainerValue.Builder setContainerBarcode(java.lang.CharSequence value) {
      validate(fields()[11], value);
      this.container_barcode = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'container_barcode' field has been set.
      * @return True if the 'container_barcode' field has been set, false otherwise.
      */
    public boolean hasContainerBarcode() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'container_barcode' field.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.ContainerValue.Builder clearContainerBarcode() {
      container_barcode = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'shipper_parcel_number' field.
      * @return The value.
      */
    public java.lang.CharSequence getShipperParcelNumber() {
      return shipper_parcel_number;
    }


    /**
      * Sets the value of the 'shipper_parcel_number' field.
      * @param value The value of 'shipper_parcel_number'.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.ContainerValue.Builder setShipperParcelNumber(java.lang.CharSequence value) {
      validate(fields()[12], value);
      this.shipper_parcel_number = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'shipper_parcel_number' field has been set.
      * @return True if the 'shipper_parcel_number' field has been set, false otherwise.
      */
    public boolean hasShipperParcelNumber() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'shipper_parcel_number' field.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.ContainerValue.Builder clearShipperParcelNumber() {
      shipper_parcel_number = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ContainerValue build() {
      try {
        ContainerValue record = new ContainerValue();
        if (auxiliary_dataBuilder != null) {
          try {
            record.auxiliary_data = this.auxiliary_dataBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("auxiliary_data"));
            throw e;
          }
        } else {
          record.auxiliary_data = fieldSetFlags()[0] ? this.auxiliary_data : (com.example.Pulsar_test.model.AuxiliaryData) defaultValue(fields()[0]);
        }
        record.reference1 = fieldSetFlags()[1] ? this.reference1 : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.reference2 = fieldSetFlags()[2] ? this.reference2 : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.reference3 = fieldSetFlags()[3] ? this.reference3 : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.created_at = fieldSetFlags()[4] ? this.created_at : (java.time.Instant) defaultValue(fields()[4]);
        record.nodes = fieldSetFlags()[5] ? this.nodes : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[5]);
        record.service_code = fieldSetFlags()[6] ? this.service_code : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.container_type = fieldSetFlags()[7] ? this.container_type : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.carrier_tracking_number = fieldSetFlags()[8] ? this.carrier_tracking_number : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.airterra_tracking_number = fieldSetFlags()[9] ? this.airterra_tracking_number : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.active_node_id = fieldSetFlags()[10] ? this.active_node_id : (java.lang.CharSequence) defaultValue(fields()[10]);
        record.container_barcode = fieldSetFlags()[11] ? this.container_barcode : (java.lang.CharSequence) defaultValue(fields()[11]);
        record.shipper_parcel_number = fieldSetFlags()[12] ? this.shipper_parcel_number : (java.lang.CharSequence) defaultValue(fields()[12]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ContainerValue>
    WRITER$ = (org.apache.avro.io.DatumWriter<ContainerValue>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ContainerValue>
    READER$ = (org.apache.avro.io.DatumReader<ContainerValue>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










