/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.Pulsar_test.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Table 63353437396533612d396630362d346635352d626235312d303766386633616630633037_sortation.container_barcode_to_id_v2 */
@org.apache.avro.specific.AvroGenerated
public class ContainerBarcodeKey extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2854714635591365383L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ContainerBarcodeKey\",\"namespace\":\"com.example.Pulsar_test.model\",\"doc\":\"Table 63353437396533612d396630362d346635352d626235312d303766386633616630633037_sortation.container_barcode_to_id_v2\",\"fields\":[{\"name\":\"container_barcode\",\"type\":\"string\"},{\"name\":\"node_id\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"type\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ContainerBarcodeKey> ENCODER =
      new BinaryMessageEncoder<ContainerBarcodeKey>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ContainerBarcodeKey> DECODER =
      new BinaryMessageDecoder<ContainerBarcodeKey>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ContainerBarcodeKey> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ContainerBarcodeKey> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ContainerBarcodeKey> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ContainerBarcodeKey>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ContainerBarcodeKey to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ContainerBarcodeKey from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ContainerBarcodeKey instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ContainerBarcodeKey fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence container_barcode;
  @Deprecated public java.lang.CharSequence node_id;
  @Deprecated public java.lang.CharSequence type;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ContainerBarcodeKey() {}

  /**
   * All-args constructor.
   * @param container_barcode The new value for container_barcode
   * @param node_id The new value for node_id
   * @param type The new value for type
   */
  public ContainerBarcodeKey(java.lang.CharSequence container_barcode, java.lang.CharSequence node_id, java.lang.CharSequence type) {
    this.container_barcode = container_barcode;
    this.node_id = node_id;
    this.type = type;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return container_barcode;
    case 1: return node_id;
    case 2: return type;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: container_barcode = (java.lang.CharSequence)value$; break;
    case 1: node_id = (java.lang.CharSequence)value$; break;
    case 2: type = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'container_barcode' field.
   * @return The value of the 'container_barcode' field.
   */
  public java.lang.CharSequence getContainerBarcode() {
    return container_barcode;
  }


  /**
   * Sets the value of the 'container_barcode' field.
   * @param value the value to set.
   */
  public void setContainerBarcode(java.lang.CharSequence value) {
    this.container_barcode = value;
  }

  /**
   * Gets the value of the 'node_id' field.
   * @return The value of the 'node_id' field.
   */
  public java.lang.CharSequence getNodeId() {
    return node_id;
  }


  /**
   * Sets the value of the 'node_id' field.
   * @param value the value to set.
   */
  public void setNodeId(java.lang.CharSequence value) {
    this.node_id = value;
  }

  /**
   * Gets the value of the 'type' field.
   * @return The value of the 'type' field.
   */
  public java.lang.CharSequence getType() {
    return type;
  }


  /**
   * Sets the value of the 'type' field.
   * @param value the value to set.
   */
  public void setType(java.lang.CharSequence value) {
    this.type = value;
  }

  /**
   * Creates a new ContainerBarcodeKey RecordBuilder.
   * @return A new ContainerBarcodeKey RecordBuilder
   */
  public static com.example.Pulsar_test.model.ContainerBarcodeKey.Builder newBuilder() {
    return new com.example.Pulsar_test.model.ContainerBarcodeKey.Builder();
  }

  /**
   * Creates a new ContainerBarcodeKey RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ContainerBarcodeKey RecordBuilder
   */
  public static com.example.Pulsar_test.model.ContainerBarcodeKey.Builder newBuilder(com.example.Pulsar_test.model.ContainerBarcodeKey.Builder other) {
    if (other == null) {
      return new com.example.Pulsar_test.model.ContainerBarcodeKey.Builder();
    } else {
      return new com.example.Pulsar_test.model.ContainerBarcodeKey.Builder(other);
    }
  }

  /**
   * Creates a new ContainerBarcodeKey RecordBuilder by copying an existing ContainerBarcodeKey instance.
   * @param other The existing instance to copy.
   * @return A new ContainerBarcodeKey RecordBuilder
   */
  public static com.example.Pulsar_test.model.ContainerBarcodeKey.Builder newBuilder(com.example.Pulsar_test.model.ContainerBarcodeKey other) {
    if (other == null) {
      return new com.example.Pulsar_test.model.ContainerBarcodeKey.Builder();
    } else {
      return new com.example.Pulsar_test.model.ContainerBarcodeKey.Builder(other);
    }
  }

  /**
   * RecordBuilder for ContainerBarcodeKey instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ContainerBarcodeKey>
    implements org.apache.avro.data.RecordBuilder<ContainerBarcodeKey> {

    private java.lang.CharSequence container_barcode;
    private java.lang.CharSequence node_id;
    private java.lang.CharSequence type;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.Pulsar_test.model.ContainerBarcodeKey.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.container_barcode)) {
        this.container_barcode = data().deepCopy(fields()[0].schema(), other.container_barcode);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.node_id)) {
        this.node_id = data().deepCopy(fields()[1].schema(), other.node_id);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.type)) {
        this.type = data().deepCopy(fields()[2].schema(), other.type);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing ContainerBarcodeKey instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.Pulsar_test.model.ContainerBarcodeKey other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.container_barcode)) {
        this.container_barcode = data().deepCopy(fields()[0].schema(), other.container_barcode);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.node_id)) {
        this.node_id = data().deepCopy(fields()[1].schema(), other.node_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.type)) {
        this.type = data().deepCopy(fields()[2].schema(), other.type);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'container_barcode' field.
      * @return The value.
      */
    public java.lang.CharSequence getContainerBarcode() {
      return container_barcode;
    }


    /**
      * Sets the value of the 'container_barcode' field.
      * @param value The value of 'container_barcode'.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.ContainerBarcodeKey.Builder setContainerBarcode(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.container_barcode = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'container_barcode' field has been set.
      * @return True if the 'container_barcode' field has been set, false otherwise.
      */
    public boolean hasContainerBarcode() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'container_barcode' field.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.ContainerBarcodeKey.Builder clearContainerBarcode() {
      container_barcode = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'node_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getNodeId() {
      return node_id;
    }


    /**
      * Sets the value of the 'node_id' field.
      * @param value The value of 'node_id'.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.ContainerBarcodeKey.Builder setNodeId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.node_id = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'node_id' field has been set.
      * @return True if the 'node_id' field has been set, false otherwise.
      */
    public boolean hasNodeId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'node_id' field.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.ContainerBarcodeKey.Builder clearNodeId() {
      node_id = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'type' field.
      * @return The value.
      */
    public java.lang.CharSequence getType() {
      return type;
    }


    /**
      * Sets the value of the 'type' field.
      * @param value The value of 'type'.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.ContainerBarcodeKey.Builder setType(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.type = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'type' field has been set.
      * @return True if the 'type' field has been set, false otherwise.
      */
    public boolean hasType() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'type' field.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.ContainerBarcodeKey.Builder clearType() {
      type = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ContainerBarcodeKey build() {
      try {
        ContainerBarcodeKey record = new ContainerBarcodeKey();
        record.container_barcode = fieldSetFlags()[0] ? this.container_barcode : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.node_id = fieldSetFlags()[1] ? this.node_id : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.type = fieldSetFlags()[2] ? this.type : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ContainerBarcodeKey>
    WRITER$ = (org.apache.avro.io.DatumWriter<ContainerBarcodeKey>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ContainerBarcodeKey>
    READER$ = (org.apache.avro.io.DatumReader<ContainerBarcodeKey>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.container_barcode);

    if (this.node_id == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.node_id);
    }

    if (this.type == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.type);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.container_barcode = in.readString(this.container_barcode instanceof Utf8 ? (Utf8)this.container_barcode : null);

      if (in.readIndex() != 1) {
        in.readNull();
        this.node_id = null;
      } else {
        this.node_id = in.readString(this.node_id instanceof Utf8 ? (Utf8)this.node_id : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.type = null;
      } else {
        this.type = in.readString(this.type instanceof Utf8 ? (Utf8)this.type : null);
      }

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.container_barcode = in.readString(this.container_barcode instanceof Utf8 ? (Utf8)this.container_barcode : null);
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.node_id = null;
          } else {
            this.node_id = in.readString(this.node_id instanceof Utf8 ? (Utf8)this.node_id : null);
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.type = null;
          } else {
            this.type = in.readString(this.type instanceof Utf8 ? (Utf8)this.type : null);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










