/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.Pulsar_test.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Table 63353437396533612d396630362d346635352d626235312d303766386633616630633037_sortation.child_to_parent_container_association */
@org.apache.avro.specific.AvroGenerated
public class ContainerParentValue extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1589799924760898683L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ContainerParentValue\",\"namespace\":\"com.example.Pulsar_test.model\",\"doc\":\"Table 63353437396533612d396630362d346635352d626235312d303766386633616630633037_sortation.child_to_parent_container_association\",\"fields\":[{\"name\":\"parent_container_id\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"active\",\"type\":[\"null\",\"boolean\"],\"default\":null},{\"name\":\"created_at\",\"type\":[\"null\",\"long\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ContainerParentValue> ENCODER =
      new BinaryMessageEncoder<ContainerParentValue>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ContainerParentValue> DECODER =
      new BinaryMessageDecoder<ContainerParentValue>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ContainerParentValue> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ContainerParentValue> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ContainerParentValue> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ContainerParentValue>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ContainerParentValue to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ContainerParentValue from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ContainerParentValue instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ContainerParentValue fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence parent_container_id;
  @Deprecated public java.lang.Boolean active;
  @Deprecated public java.lang.Long created_at;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ContainerParentValue() {}

  /**
   * All-args constructor.
   * @param parent_container_id The new value for parent_container_id
   * @param active The new value for active
   * @param created_at The new value for created_at
   */
  public ContainerParentValue(java.lang.CharSequence parent_container_id, java.lang.Boolean active, java.lang.Long created_at) {
    this.parent_container_id = parent_container_id;
    this.active = active;
    this.created_at = created_at;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return parent_container_id;
    case 1: return active;
    case 2: return created_at;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: parent_container_id = (java.lang.CharSequence)value$; break;
    case 1: active = (java.lang.Boolean)value$; break;
    case 2: created_at = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'parent_container_id' field.
   * @return The value of the 'parent_container_id' field.
   */
  public java.lang.CharSequence getParentContainerId() {
    return parent_container_id;
  }


  /**
   * Sets the value of the 'parent_container_id' field.
   * @param value the value to set.
   */
  public void setParentContainerId(java.lang.CharSequence value) {
    this.parent_container_id = value;
  }

  /**
   * Gets the value of the 'active' field.
   * @return The value of the 'active' field.
   */
  public java.lang.Boolean getActive() {
    return active;
  }


  /**
   * Sets the value of the 'active' field.
   * @param value the value to set.
   */
  public void setActive(java.lang.Boolean value) {
    this.active = value;
  }

  /**
   * Gets the value of the 'created_at' field.
   * @return The value of the 'created_at' field.
   */
  public java.lang.Long getCreatedAt() {
    return created_at;
  }


  /**
   * Sets the value of the 'created_at' field.
   * @param value the value to set.
   */
  public void setCreatedAt(java.lang.Long value) {
    this.created_at = value;
  }

  /**
   * Creates a new ContainerParentValue RecordBuilder.
   * @return A new ContainerParentValue RecordBuilder
   */
  public static com.example.Pulsar_test.model.ContainerParentValue.Builder newBuilder() {
    return new com.example.Pulsar_test.model.ContainerParentValue.Builder();
  }

  /**
   * Creates a new ContainerParentValue RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ContainerParentValue RecordBuilder
   */
  public static com.example.Pulsar_test.model.ContainerParentValue.Builder newBuilder(com.example.Pulsar_test.model.ContainerParentValue.Builder other) {
    if (other == null) {
      return new com.example.Pulsar_test.model.ContainerParentValue.Builder();
    } else {
      return new com.example.Pulsar_test.model.ContainerParentValue.Builder(other);
    }
  }

  /**
   * Creates a new ContainerParentValue RecordBuilder by copying an existing ContainerParentValue instance.
   * @param other The existing instance to copy.
   * @return A new ContainerParentValue RecordBuilder
   */
  public static com.example.Pulsar_test.model.ContainerParentValue.Builder newBuilder(com.example.Pulsar_test.model.ContainerParentValue other) {
    if (other == null) {
      return new com.example.Pulsar_test.model.ContainerParentValue.Builder();
    } else {
      return new com.example.Pulsar_test.model.ContainerParentValue.Builder(other);
    }
  }

  /**
   * RecordBuilder for ContainerParentValue instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ContainerParentValue>
    implements org.apache.avro.data.RecordBuilder<ContainerParentValue> {

    private java.lang.CharSequence parent_container_id;
    private java.lang.Boolean active;
    private java.lang.Long created_at;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.Pulsar_test.model.ContainerParentValue.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.parent_container_id)) {
        this.parent_container_id = data().deepCopy(fields()[0].schema(), other.parent_container_id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.active)) {
        this.active = data().deepCopy(fields()[1].schema(), other.active);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.created_at)) {
        this.created_at = data().deepCopy(fields()[2].schema(), other.created_at);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing ContainerParentValue instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.Pulsar_test.model.ContainerParentValue other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.parent_container_id)) {
        this.parent_container_id = data().deepCopy(fields()[0].schema(), other.parent_container_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.active)) {
        this.active = data().deepCopy(fields()[1].schema(), other.active);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.created_at)) {
        this.created_at = data().deepCopy(fields()[2].schema(), other.created_at);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'parent_container_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getParentContainerId() {
      return parent_container_id;
    }


    /**
      * Sets the value of the 'parent_container_id' field.
      * @param value The value of 'parent_container_id'.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.ContainerParentValue.Builder setParentContainerId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.parent_container_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'parent_container_id' field has been set.
      * @return True if the 'parent_container_id' field has been set, false otherwise.
      */
    public boolean hasParentContainerId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'parent_container_id' field.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.ContainerParentValue.Builder clearParentContainerId() {
      parent_container_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'active' field.
      * @return The value.
      */
    public java.lang.Boolean getActive() {
      return active;
    }


    /**
      * Sets the value of the 'active' field.
      * @param value The value of 'active'.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.ContainerParentValue.Builder setActive(java.lang.Boolean value) {
      validate(fields()[1], value);
      this.active = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'active' field has been set.
      * @return True if the 'active' field has been set, false otherwise.
      */
    public boolean hasActive() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'active' field.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.ContainerParentValue.Builder clearActive() {
      active = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'created_at' field.
      * @return The value.
      */
    public java.lang.Long getCreatedAt() {
      return created_at;
    }


    /**
      * Sets the value of the 'created_at' field.
      * @param value The value of 'created_at'.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.ContainerParentValue.Builder setCreatedAt(java.lang.Long value) {
      validate(fields()[2], value);
      this.created_at = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'created_at' field has been set.
      * @return True if the 'created_at' field has been set, false otherwise.
      */
    public boolean hasCreatedAt() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'created_at' field.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.ContainerParentValue.Builder clearCreatedAt() {
      created_at = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ContainerParentValue build() {
      try {
        ContainerParentValue record = new ContainerParentValue();
        record.parent_container_id = fieldSetFlags()[0] ? this.parent_container_id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.active = fieldSetFlags()[1] ? this.active : (java.lang.Boolean) defaultValue(fields()[1]);
        record.created_at = fieldSetFlags()[2] ? this.created_at : (java.lang.Long) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ContainerParentValue>
    WRITER$ = (org.apache.avro.io.DatumWriter<ContainerParentValue>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ContainerParentValue>
    READER$ = (org.apache.avro.io.DatumReader<ContainerParentValue>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.parent_container_id == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.parent_container_id);
    }

    if (this.active == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeBoolean(this.active);
    }

    if (this.created_at == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.created_at);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.parent_container_id = null;
      } else {
        this.parent_container_id = in.readString(this.parent_container_id instanceof Utf8 ? (Utf8)this.parent_container_id : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.active = null;
      } else {
        this.active = in.readBoolean();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.created_at = null;
      } else {
        this.created_at = in.readLong();
      }

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.parent_container_id = null;
          } else {
            this.parent_container_id = in.readString(this.parent_container_id instanceof Utf8 ? (Utf8)this.parent_container_id : null);
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.active = null;
          } else {
            this.active = in.readBoolean();
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.created_at = null;
          } else {
            this.created_at = in.readLong();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










