/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.Pulsar_test.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Table 63353437396533612d396630362d346635352d626235312d303766386633616630633037_sortation.container_plan */
@org.apache.avro.specific.AvroGenerated
public class ContainerPlanKey extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2844434874986877997L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ContainerPlanKey\",\"namespace\":\"com.example.Pulsar_test.model\",\"doc\":\"Table 63353437396533612d396630362d346635352d626235312d303766386633616630633037_sortation.container_plan\",\"fields\":[{\"name\":\"container_id\",\"type\":\"string\"},{\"name\":\"node_id\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ContainerPlanKey> ENCODER =
      new BinaryMessageEncoder<ContainerPlanKey>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ContainerPlanKey> DECODER =
      new BinaryMessageDecoder<ContainerPlanKey>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ContainerPlanKey> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ContainerPlanKey> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ContainerPlanKey> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ContainerPlanKey>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ContainerPlanKey to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ContainerPlanKey from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ContainerPlanKey instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ContainerPlanKey fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence container_id;
  @Deprecated public java.lang.CharSequence node_id;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ContainerPlanKey() {}

  /**
   * All-args constructor.
   * @param container_id The new value for container_id
   * @param node_id The new value for node_id
   */
  public ContainerPlanKey(java.lang.CharSequence container_id, java.lang.CharSequence node_id) {
    this.container_id = container_id;
    this.node_id = node_id;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return container_id;
    case 1: return node_id;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: container_id = (java.lang.CharSequence)value$; break;
    case 1: node_id = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'container_id' field.
   * @return The value of the 'container_id' field.
   */
  public java.lang.CharSequence getContainerId() {
    return container_id;
  }


  /**
   * Sets the value of the 'container_id' field.
   * @param value the value to set.
   */
  public void setContainerId(java.lang.CharSequence value) {
    this.container_id = value;
  }

  /**
   * Gets the value of the 'node_id' field.
   * @return The value of the 'node_id' field.
   */
  public java.lang.CharSequence getNodeId() {
    return node_id;
  }


  /**
   * Sets the value of the 'node_id' field.
   * @param value the value to set.
   */
  public void setNodeId(java.lang.CharSequence value) {
    this.node_id = value;
  }

  /**
   * Creates a new ContainerPlanKey RecordBuilder.
   * @return A new ContainerPlanKey RecordBuilder
   */
  public static com.example.Pulsar_test.model.ContainerPlanKey.Builder newBuilder() {
    return new com.example.Pulsar_test.model.ContainerPlanKey.Builder();
  }

  /**
   * Creates a new ContainerPlanKey RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ContainerPlanKey RecordBuilder
   */
  public static com.example.Pulsar_test.model.ContainerPlanKey.Builder newBuilder(com.example.Pulsar_test.model.ContainerPlanKey.Builder other) {
    if (other == null) {
      return new com.example.Pulsar_test.model.ContainerPlanKey.Builder();
    } else {
      return new com.example.Pulsar_test.model.ContainerPlanKey.Builder(other);
    }
  }

  /**
   * Creates a new ContainerPlanKey RecordBuilder by copying an existing ContainerPlanKey instance.
   * @param other The existing instance to copy.
   * @return A new ContainerPlanKey RecordBuilder
   */
  public static com.example.Pulsar_test.model.ContainerPlanKey.Builder newBuilder(com.example.Pulsar_test.model.ContainerPlanKey other) {
    if (other == null) {
      return new com.example.Pulsar_test.model.ContainerPlanKey.Builder();
    } else {
      return new com.example.Pulsar_test.model.ContainerPlanKey.Builder(other);
    }
  }

  /**
   * RecordBuilder for ContainerPlanKey instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ContainerPlanKey>
    implements org.apache.avro.data.RecordBuilder<ContainerPlanKey> {

    private java.lang.CharSequence container_id;
    private java.lang.CharSequence node_id;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.Pulsar_test.model.ContainerPlanKey.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.container_id)) {
        this.container_id = data().deepCopy(fields()[0].schema(), other.container_id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.node_id)) {
        this.node_id = data().deepCopy(fields()[1].schema(), other.node_id);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing ContainerPlanKey instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.Pulsar_test.model.ContainerPlanKey other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.container_id)) {
        this.container_id = data().deepCopy(fields()[0].schema(), other.container_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.node_id)) {
        this.node_id = data().deepCopy(fields()[1].schema(), other.node_id);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'container_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getContainerId() {
      return container_id;
    }


    /**
      * Sets the value of the 'container_id' field.
      * @param value The value of 'container_id'.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.ContainerPlanKey.Builder setContainerId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.container_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'container_id' field has been set.
      * @return True if the 'container_id' field has been set, false otherwise.
      */
    public boolean hasContainerId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'container_id' field.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.ContainerPlanKey.Builder clearContainerId() {
      container_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'node_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getNodeId() {
      return node_id;
    }


    /**
      * Sets the value of the 'node_id' field.
      * @param value The value of 'node_id'.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.ContainerPlanKey.Builder setNodeId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.node_id = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'node_id' field has been set.
      * @return True if the 'node_id' field has been set, false otherwise.
      */
    public boolean hasNodeId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'node_id' field.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.ContainerPlanKey.Builder clearNodeId() {
      node_id = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ContainerPlanKey build() {
      try {
        ContainerPlanKey record = new ContainerPlanKey();
        record.container_id = fieldSetFlags()[0] ? this.container_id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.node_id = fieldSetFlags()[1] ? this.node_id : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ContainerPlanKey>
    WRITER$ = (org.apache.avro.io.DatumWriter<ContainerPlanKey>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ContainerPlanKey>
    READER$ = (org.apache.avro.io.DatumReader<ContainerPlanKey>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.container_id);

    if (this.node_id == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.node_id);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.container_id = in.readString(this.container_id instanceof Utf8 ? (Utf8)this.container_id : null);

      if (in.readIndex() != 1) {
        in.readNull();
        this.node_id = null;
      } else {
        this.node_id = in.readString(this.node_id instanceof Utf8 ? (Utf8)this.node_id : null);
      }

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.container_id = in.readString(this.container_id instanceof Utf8 ? (Utf8)this.container_id : null);
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.node_id = null;
          } else {
            this.node_id = in.readString(this.node_id instanceof Utf8 ? (Utf8)this.node_id : null);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










