/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.Pulsar_test.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Table 63353437396533612d396630362d346635352d626235312d303766386633616630633037_sortation.container_history */
@org.apache.avro.specific.AvroGenerated
public class ContainerHistoryValue extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4517524953352094909L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ContainerHistoryValue\",\"namespace\":\"com.example.Pulsar_test.model\",\"doc\":\"Table 63353437396533612d396630362d346635352d626235312d303766386633616630633037_sortation.container_history\",\"fields\":[{\"name\":\"notes\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"area_id\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"associate_id\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ContainerHistoryValue> ENCODER =
      new BinaryMessageEncoder<ContainerHistoryValue>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ContainerHistoryValue> DECODER =
      new BinaryMessageDecoder<ContainerHistoryValue>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ContainerHistoryValue> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ContainerHistoryValue> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ContainerHistoryValue> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ContainerHistoryValue>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ContainerHistoryValue to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ContainerHistoryValue from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ContainerHistoryValue instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ContainerHistoryValue fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence notes;
  @Deprecated public java.lang.CharSequence area_id;
  @Deprecated public java.lang.CharSequence associate_id;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ContainerHistoryValue() {}

  /**
   * All-args constructor.
   * @param notes The new value for notes
   * @param area_id The new value for area_id
   * @param associate_id The new value for associate_id
   */
  public ContainerHistoryValue(java.lang.CharSequence notes, java.lang.CharSequence area_id, java.lang.CharSequence associate_id) {
    this.notes = notes;
    this.area_id = area_id;
    this.associate_id = associate_id;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return notes;
    case 1: return area_id;
    case 2: return associate_id;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: notes = (java.lang.CharSequence)value$; break;
    case 1: area_id = (java.lang.CharSequence)value$; break;
    case 2: associate_id = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'notes' field.
   * @return The value of the 'notes' field.
   */
  public java.lang.CharSequence getNotes() {
    return notes;
  }


  /**
   * Sets the value of the 'notes' field.
   * @param value the value to set.
   */
  public void setNotes(java.lang.CharSequence value) {
    this.notes = value;
  }

  /**
   * Gets the value of the 'area_id' field.
   * @return The value of the 'area_id' field.
   */
  public java.lang.CharSequence getAreaId() {
    return area_id;
  }


  /**
   * Sets the value of the 'area_id' field.
   * @param value the value to set.
   */
  public void setAreaId(java.lang.CharSequence value) {
    this.area_id = value;
  }

  /**
   * Gets the value of the 'associate_id' field.
   * @return The value of the 'associate_id' field.
   */
  public java.lang.CharSequence getAssociateId() {
    return associate_id;
  }


  /**
   * Sets the value of the 'associate_id' field.
   * @param value the value to set.
   */
  public void setAssociateId(java.lang.CharSequence value) {
    this.associate_id = value;
  }

  /**
   * Creates a new ContainerHistoryValue RecordBuilder.
   * @return A new ContainerHistoryValue RecordBuilder
   */
  public static com.example.Pulsar_test.model.ContainerHistoryValue.Builder newBuilder() {
    return new com.example.Pulsar_test.model.ContainerHistoryValue.Builder();
  }

  /**
   * Creates a new ContainerHistoryValue RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ContainerHistoryValue RecordBuilder
   */
  public static com.example.Pulsar_test.model.ContainerHistoryValue.Builder newBuilder(com.example.Pulsar_test.model.ContainerHistoryValue.Builder other) {
    if (other == null) {
      return new com.example.Pulsar_test.model.ContainerHistoryValue.Builder();
    } else {
      return new com.example.Pulsar_test.model.ContainerHistoryValue.Builder(other);
    }
  }

  /**
   * Creates a new ContainerHistoryValue RecordBuilder by copying an existing ContainerHistoryValue instance.
   * @param other The existing instance to copy.
   * @return A new ContainerHistoryValue RecordBuilder
   */
  public static com.example.Pulsar_test.model.ContainerHistoryValue.Builder newBuilder(com.example.Pulsar_test.model.ContainerHistoryValue other) {
    if (other == null) {
      return new com.example.Pulsar_test.model.ContainerHistoryValue.Builder();
    } else {
      return new com.example.Pulsar_test.model.ContainerHistoryValue.Builder(other);
    }
  }

  /**
   * RecordBuilder for ContainerHistoryValue instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ContainerHistoryValue>
    implements org.apache.avro.data.RecordBuilder<ContainerHistoryValue> {

    private java.lang.CharSequence notes;
    private java.lang.CharSequence area_id;
    private java.lang.CharSequence associate_id;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.Pulsar_test.model.ContainerHistoryValue.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.notes)) {
        this.notes = data().deepCopy(fields()[0].schema(), other.notes);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.area_id)) {
        this.area_id = data().deepCopy(fields()[1].schema(), other.area_id);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.associate_id)) {
        this.associate_id = data().deepCopy(fields()[2].schema(), other.associate_id);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing ContainerHistoryValue instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.Pulsar_test.model.ContainerHistoryValue other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.notes)) {
        this.notes = data().deepCopy(fields()[0].schema(), other.notes);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.area_id)) {
        this.area_id = data().deepCopy(fields()[1].schema(), other.area_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.associate_id)) {
        this.associate_id = data().deepCopy(fields()[2].schema(), other.associate_id);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'notes' field.
      * @return The value.
      */
    public java.lang.CharSequence getNotes() {
      return notes;
    }


    /**
      * Sets the value of the 'notes' field.
      * @param value The value of 'notes'.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.ContainerHistoryValue.Builder setNotes(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.notes = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'notes' field has been set.
      * @return True if the 'notes' field has been set, false otherwise.
      */
    public boolean hasNotes() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'notes' field.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.ContainerHistoryValue.Builder clearNotes() {
      notes = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'area_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getAreaId() {
      return area_id;
    }


    /**
      * Sets the value of the 'area_id' field.
      * @param value The value of 'area_id'.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.ContainerHistoryValue.Builder setAreaId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.area_id = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'area_id' field has been set.
      * @return True if the 'area_id' field has been set, false otherwise.
      */
    public boolean hasAreaId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'area_id' field.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.ContainerHistoryValue.Builder clearAreaId() {
      area_id = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'associate_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getAssociateId() {
      return associate_id;
    }


    /**
      * Sets the value of the 'associate_id' field.
      * @param value The value of 'associate_id'.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.ContainerHistoryValue.Builder setAssociateId(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.associate_id = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'associate_id' field has been set.
      * @return True if the 'associate_id' field has been set, false otherwise.
      */
    public boolean hasAssociateId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'associate_id' field.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.ContainerHistoryValue.Builder clearAssociateId() {
      associate_id = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ContainerHistoryValue build() {
      try {
        ContainerHistoryValue record = new ContainerHistoryValue();
        record.notes = fieldSetFlags()[0] ? this.notes : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.area_id = fieldSetFlags()[1] ? this.area_id : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.associate_id = fieldSetFlags()[2] ? this.associate_id : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ContainerHistoryValue>
    WRITER$ = (org.apache.avro.io.DatumWriter<ContainerHistoryValue>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ContainerHistoryValue>
    READER$ = (org.apache.avro.io.DatumReader<ContainerHistoryValue>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.notes == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.notes);
    }

    if (this.area_id == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.area_id);
    }

    if (this.associate_id == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.associate_id);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.notes = null;
      } else {
        this.notes = in.readString(this.notes instanceof Utf8 ? (Utf8)this.notes : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.area_id = null;
      } else {
        this.area_id = in.readString(this.area_id instanceof Utf8 ? (Utf8)this.area_id : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.associate_id = null;
      } else {
        this.associate_id = in.readString(this.associate_id instanceof Utf8 ? (Utf8)this.associate_id : null);
      }

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.notes = null;
          } else {
            this.notes = in.readString(this.notes instanceof Utf8 ? (Utf8)this.notes : null);
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.area_id = null;
          } else {
            this.area_id = in.readString(this.area_id instanceof Utf8 ? (Utf8)this.area_id : null);
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.associate_id = null;
          } else {
            this.associate_id = in.readString(this.associate_id instanceof Utf8 ? (Utf8)this.associate_id : null);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










