/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.Pulsar_test.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Table 63353437396533612d396630362d346635352d626235312d303766386633616630633037_sortation.child_to_parent_container_association */
@org.apache.avro.specific.AvroGenerated
public class ContainerParentKey extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8328651141700134564L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ContainerParentKey\",\"namespace\":\"com.example.Pulsar_test.model\",\"doc\":\"Table 63353437396533612d396630362d346635352d626235312d303766386633616630633037_sortation.child_to_parent_container_association\",\"fields\":[{\"name\":\"child_container_id\",\"type\":\"string\"},{\"name\":\"node_id\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ContainerParentKey> ENCODER =
      new BinaryMessageEncoder<ContainerParentKey>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ContainerParentKey> DECODER =
      new BinaryMessageDecoder<ContainerParentKey>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ContainerParentKey> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ContainerParentKey> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ContainerParentKey> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ContainerParentKey>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ContainerParentKey to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ContainerParentKey from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ContainerParentKey instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ContainerParentKey fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence child_container_id;
  @Deprecated public java.lang.CharSequence node_id;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ContainerParentKey() {}

  /**
   * All-args constructor.
   * @param child_container_id The new value for child_container_id
   * @param node_id The new value for node_id
   */
  public ContainerParentKey(java.lang.CharSequence child_container_id, java.lang.CharSequence node_id) {
    this.child_container_id = child_container_id;
    this.node_id = node_id;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return child_container_id;
    case 1: return node_id;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: child_container_id = (java.lang.CharSequence)value$; break;
    case 1: node_id = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'child_container_id' field.
   * @return The value of the 'child_container_id' field.
   */
  public java.lang.CharSequence getChildContainerId() {
    return child_container_id;
  }


  /**
   * Sets the value of the 'child_container_id' field.
   * @param value the value to set.
   */
  public void setChildContainerId(java.lang.CharSequence value) {
    this.child_container_id = value;
  }

  /**
   * Gets the value of the 'node_id' field.
   * @return The value of the 'node_id' field.
   */
  public java.lang.CharSequence getNodeId() {
    return node_id;
  }


  /**
   * Sets the value of the 'node_id' field.
   * @param value the value to set.
   */
  public void setNodeId(java.lang.CharSequence value) {
    this.node_id = value;
  }

  /**
   * Creates a new ContainerParentKey RecordBuilder.
   * @return A new ContainerParentKey RecordBuilder
   */
  public static com.example.Pulsar_test.model.ContainerParentKey.Builder newBuilder() {
    return new com.example.Pulsar_test.model.ContainerParentKey.Builder();
  }

  /**
   * Creates a new ContainerParentKey RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ContainerParentKey RecordBuilder
   */
  public static com.example.Pulsar_test.model.ContainerParentKey.Builder newBuilder(com.example.Pulsar_test.model.ContainerParentKey.Builder other) {
    if (other == null) {
      return new com.example.Pulsar_test.model.ContainerParentKey.Builder();
    } else {
      return new com.example.Pulsar_test.model.ContainerParentKey.Builder(other);
    }
  }

  /**
   * Creates a new ContainerParentKey RecordBuilder by copying an existing ContainerParentKey instance.
   * @param other The existing instance to copy.
   * @return A new ContainerParentKey RecordBuilder
   */
  public static com.example.Pulsar_test.model.ContainerParentKey.Builder newBuilder(com.example.Pulsar_test.model.ContainerParentKey other) {
    if (other == null) {
      return new com.example.Pulsar_test.model.ContainerParentKey.Builder();
    } else {
      return new com.example.Pulsar_test.model.ContainerParentKey.Builder(other);
    }
  }

  /**
   * RecordBuilder for ContainerParentKey instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ContainerParentKey>
    implements org.apache.avro.data.RecordBuilder<ContainerParentKey> {

    private java.lang.CharSequence child_container_id;
    private java.lang.CharSequence node_id;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.Pulsar_test.model.ContainerParentKey.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.child_container_id)) {
        this.child_container_id = data().deepCopy(fields()[0].schema(), other.child_container_id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.node_id)) {
        this.node_id = data().deepCopy(fields()[1].schema(), other.node_id);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing ContainerParentKey instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.Pulsar_test.model.ContainerParentKey other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.child_container_id)) {
        this.child_container_id = data().deepCopy(fields()[0].schema(), other.child_container_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.node_id)) {
        this.node_id = data().deepCopy(fields()[1].schema(), other.node_id);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'child_container_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getChildContainerId() {
      return child_container_id;
    }


    /**
      * Sets the value of the 'child_container_id' field.
      * @param value The value of 'child_container_id'.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.ContainerParentKey.Builder setChildContainerId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.child_container_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'child_container_id' field has been set.
      * @return True if the 'child_container_id' field has been set, false otherwise.
      */
    public boolean hasChildContainerId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'child_container_id' field.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.ContainerParentKey.Builder clearChildContainerId() {
      child_container_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'node_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getNodeId() {
      return node_id;
    }


    /**
      * Sets the value of the 'node_id' field.
      * @param value The value of 'node_id'.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.ContainerParentKey.Builder setNodeId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.node_id = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'node_id' field has been set.
      * @return True if the 'node_id' field has been set, false otherwise.
      */
    public boolean hasNodeId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'node_id' field.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.ContainerParentKey.Builder clearNodeId() {
      node_id = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ContainerParentKey build() {
      try {
        ContainerParentKey record = new ContainerParentKey();
        record.child_container_id = fieldSetFlags()[0] ? this.child_container_id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.node_id = fieldSetFlags()[1] ? this.node_id : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ContainerParentKey>
    WRITER$ = (org.apache.avro.io.DatumWriter<ContainerParentKey>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ContainerParentKey>
    READER$ = (org.apache.avro.io.DatumReader<ContainerParentKey>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.child_container_id);

    if (this.node_id == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.node_id);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.child_container_id = in.readString(this.child_container_id instanceof Utf8 ? (Utf8)this.child_container_id : null);

      if (in.readIndex() != 1) {
        in.readNull();
        this.node_id = null;
      } else {
        this.node_id = in.readString(this.node_id instanceof Utf8 ? (Utf8)this.node_id : null);
      }

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.child_container_id = in.readString(this.child_container_id instanceof Utf8 ? (Utf8)this.child_container_id : null);
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.node_id = null;
          } else {
            this.node_id = in.readString(this.node_id instanceof Utf8 ? (Utf8)this.node_id : null);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










