/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.Pulsar_test.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Table 63353437396533612d396630362d346635352d626235312d303766386633616630633037_sortation.container_barcode_to_id_v2 */
@org.apache.avro.specific.AvroGenerated
public class ContainerBarcodeValue extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 9019844721961885968L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ContainerBarcodeValue\",\"namespace\":\"com.example.Pulsar_test.model\",\"doc\":\"Table 63353437396533612d396630362d346635352d626235312d303766386633616630633037_sortation.container_barcode_to_id_v2\",\"fields\":[{\"name\":\"container_id\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"isunique\",\"type\":[\"null\",\"boolean\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ContainerBarcodeValue> ENCODER =
      new BinaryMessageEncoder<ContainerBarcodeValue>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ContainerBarcodeValue> DECODER =
      new BinaryMessageDecoder<ContainerBarcodeValue>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ContainerBarcodeValue> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ContainerBarcodeValue> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ContainerBarcodeValue> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ContainerBarcodeValue>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ContainerBarcodeValue to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ContainerBarcodeValue from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ContainerBarcodeValue instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ContainerBarcodeValue fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence container_id;
  @Deprecated public java.lang.Boolean isunique;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ContainerBarcodeValue() {}

  /**
   * All-args constructor.
   * @param container_id The new value for container_id
   * @param isunique The new value for isunique
   */
  public ContainerBarcodeValue(java.lang.CharSequence container_id, java.lang.Boolean isunique) {
    this.container_id = container_id;
    this.isunique = isunique;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return container_id;
    case 1: return isunique;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: container_id = (java.lang.CharSequence)value$; break;
    case 1: isunique = (java.lang.Boolean)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'container_id' field.
   * @return The value of the 'container_id' field.
   */
  public java.lang.CharSequence getContainerId() {
    return container_id;
  }


  /**
   * Sets the value of the 'container_id' field.
   * @param value the value to set.
   */
  public void setContainerId(java.lang.CharSequence value) {
    this.container_id = value;
  }

  /**
   * Gets the value of the 'isunique' field.
   * @return The value of the 'isunique' field.
   */
  public java.lang.Boolean getIsunique() {
    return isunique;
  }


  /**
   * Sets the value of the 'isunique' field.
   * @param value the value to set.
   */
  public void setIsunique(java.lang.Boolean value) {
    this.isunique = value;
  }

  /**
   * Creates a new ContainerBarcodeValue RecordBuilder.
   * @return A new ContainerBarcodeValue RecordBuilder
   */
  public static com.example.Pulsar_test.model.ContainerBarcodeValue.Builder newBuilder() {
    return new com.example.Pulsar_test.model.ContainerBarcodeValue.Builder();
  }

  /**
   * Creates a new ContainerBarcodeValue RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ContainerBarcodeValue RecordBuilder
   */
  public static com.example.Pulsar_test.model.ContainerBarcodeValue.Builder newBuilder(com.example.Pulsar_test.model.ContainerBarcodeValue.Builder other) {
    if (other == null) {
      return new com.example.Pulsar_test.model.ContainerBarcodeValue.Builder();
    } else {
      return new com.example.Pulsar_test.model.ContainerBarcodeValue.Builder(other);
    }
  }

  /**
   * Creates a new ContainerBarcodeValue RecordBuilder by copying an existing ContainerBarcodeValue instance.
   * @param other The existing instance to copy.
   * @return A new ContainerBarcodeValue RecordBuilder
   */
  public static com.example.Pulsar_test.model.ContainerBarcodeValue.Builder newBuilder(com.example.Pulsar_test.model.ContainerBarcodeValue other) {
    if (other == null) {
      return new com.example.Pulsar_test.model.ContainerBarcodeValue.Builder();
    } else {
      return new com.example.Pulsar_test.model.ContainerBarcodeValue.Builder(other);
    }
  }

  /**
   * RecordBuilder for ContainerBarcodeValue instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ContainerBarcodeValue>
    implements org.apache.avro.data.RecordBuilder<ContainerBarcodeValue> {

    private java.lang.CharSequence container_id;
    private java.lang.Boolean isunique;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.Pulsar_test.model.ContainerBarcodeValue.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.container_id)) {
        this.container_id = data().deepCopy(fields()[0].schema(), other.container_id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.isunique)) {
        this.isunique = data().deepCopy(fields()[1].schema(), other.isunique);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing ContainerBarcodeValue instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.Pulsar_test.model.ContainerBarcodeValue other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.container_id)) {
        this.container_id = data().deepCopy(fields()[0].schema(), other.container_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.isunique)) {
        this.isunique = data().deepCopy(fields()[1].schema(), other.isunique);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'container_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getContainerId() {
      return container_id;
    }


    /**
      * Sets the value of the 'container_id' field.
      * @param value The value of 'container_id'.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.ContainerBarcodeValue.Builder setContainerId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.container_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'container_id' field has been set.
      * @return True if the 'container_id' field has been set, false otherwise.
      */
    public boolean hasContainerId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'container_id' field.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.ContainerBarcodeValue.Builder clearContainerId() {
      container_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'isunique' field.
      * @return The value.
      */
    public java.lang.Boolean getIsunique() {
      return isunique;
    }


    /**
      * Sets the value of the 'isunique' field.
      * @param value The value of 'isunique'.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.ContainerBarcodeValue.Builder setIsunique(java.lang.Boolean value) {
      validate(fields()[1], value);
      this.isunique = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'isunique' field has been set.
      * @return True if the 'isunique' field has been set, false otherwise.
      */
    public boolean hasIsunique() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'isunique' field.
      * @return This builder.
      */
    public com.example.Pulsar_test.model.ContainerBarcodeValue.Builder clearIsunique() {
      isunique = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ContainerBarcodeValue build() {
      try {
        ContainerBarcodeValue record = new ContainerBarcodeValue();
        record.container_id = fieldSetFlags()[0] ? this.container_id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.isunique = fieldSetFlags()[1] ? this.isunique : (java.lang.Boolean) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ContainerBarcodeValue>
    WRITER$ = (org.apache.avro.io.DatumWriter<ContainerBarcodeValue>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ContainerBarcodeValue>
    READER$ = (org.apache.avro.io.DatumReader<ContainerBarcodeValue>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.container_id == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.container_id);
    }

    if (this.isunique == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeBoolean(this.isunique);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.container_id = null;
      } else {
        this.container_id = in.readString(this.container_id instanceof Utf8 ? (Utf8)this.container_id : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.isunique = null;
      } else {
        this.isunique = in.readBoolean();
      }

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.container_id = null;
          } else {
            this.container_id = in.readString(this.container_id instanceof Utf8 ? (Utf8)this.container_id : null);
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.isunique = null;
          } else {
            this.isunique = in.readBoolean();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










